// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxbhzbeugzblognrdfgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4Ymh6YmV1Z3pibG9nbnJkZmd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNzc4MzQsImV4cCI6MjA2NTg1MzgzNH0.psKW7VEz_VkK5SGyy0twQHfpk-NtY6vfFyy1emB2TMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);